---
# tasks file for prod
- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - default-jdk
    - tomcat8

- name: Copy .war-file
  synchronize:
    src: "/work/target/hello-1.0.war"
    dest: "{{ dest_folder }}"
  notify:
    - restart tomcat